"""
content.py — All user-facing text and image URLs for LizaPillsBot.

Keeping content separate from logic means you can update phrases or add new
images without touching any bot logic. Simply edit the lists below.
"""

# ── Yandex Disk image pools ───────────────────────────────────────────────────
IMAGES = {
    'day': [
        'https://disk.yandex.com/i/BbqngpQgiPSwBg',
        'https://disk.yandex.com/i/ffSLJVhwR74MVw',
        'https://disk.yandex.com/i/KzCaEdyeJh8ABg',
        'https://disk.yandex.com/i/cwvEcsrtjuakYQ',
        'https://disk.yandex.com/i/0XKn7eIdLx23rg',
        'https://disk.yandex.com/i/Kz5KQB9S2L16yw',
        'https://disk.yandex.com/i/66lF6V4iMt-sGw',
        'https://disk.yandex.com/i/Nj6zzd5cOd1uxQ',
        'https://disk.yandex.com/i/HWC2-PZ81whW6A',
        'https://disk.yandex.com/i/lxegC8DNCGBB-Q',
        'https://disk.yandex.com/i/wmgt-sIAAMUjfg',
        'https://disk.yandex.com/i/SanJoAwqCaBQ0g',
        'https://disk.yandex.com/i/DJ_ymVqUX3puxg',
        'https://disk.yandex.com/i/mVRlGNReTTgNBg',
        'https://disk.yandex.com/i/Fm1cGL5d8YIjKQ',
        'https://disk.yandex.com/i/EB9DHJK6StjZxQ',
        'https://disk.yandex.com/i/rN-3FkE81h5VIA',
        'https://disk.yandex.com/i/cBCItGs8iY6Vzg',
        'https://disk.yandex.com/i/Wl9ZTCw7WMVAPA',
        'https://disk.yandex.com/i/HdLq1lryRxt1SA',
        'https://disk.yandex.com/i/CfJJ5JSypxFaSA',
        'https://disk.yandex.com/i/X5UX7w4UdyBdyQ',
        'https://disk.yandex.com/i/5yj6tT2SGQQUuA',
        'https://disk.yandex.com/i/s1wRC_im_nsogQ',
        'https://disk.yandex.com/i/ZcxEuAD5d78GPQ',
        'https://disk.yandex.com/i/bFTn5huLJw9Tdw',
        'https://disk.yandex.com/i/hq6V_5SYb787jw',
        'https://disk.yandex.com/i/DHAIHK_2BLhJ2g',
        'https://disk.yandex.com/i/TLWGpt4qj8GKFA',
        'https://disk.yandex.com/i/k0VHlSgn-fePug',
        'https://disk.yandex.com/i/YfdLpd7SwgvjTg',
        'https://disk.yandex.com/i/xc-JWe8j_vhGBw',
        'https://disk.yandex.com/i/SeyuL9knnJe3oA',
        'https://disk.yandex.com/i/VRIQcYYs0HXxcQ',
        'https://disk.yandex.com/i/BDBC3Tln4L7Rwg',
        'https://disk.yandex.com/i/Mb35Ww54FrQkkQ',
        'https://disk.yandex.com/i/me4ZjWR1lqoXeQ',
        'https://disk.yandex.com/i/JQU7hGoKl8CBFA',
        'https://disk.yandex.com/i/BQApkdlVc7tgqQ',
        'https://disk.yandex.com/i/K8mGfE7QU2lDlA',
        'https://disk.yandex.com/i/nbHnabFVi1tzNA',
        'https://disk.yandex.com/i/66lGPHDJvNoLIg',
        'https://disk.yandex.com/i/mO004vbcdGQsSw',
        'https://disk.yandex.com/i/VlICaoUuYIEL9Q',
        'https://disk.yandex.com/i/LfGFOsgwny8GEQ',
        'https://disk.yandex.com/i/aERYx6VLr74LnA',
        'https://disk.yandex.com/i/U2B8Hzm6uA5Mcw',
        'https://disk.yandex.com/i/ohWGsn07qEwkfA',
        'https://disk.yandex.com/i/CLt5epRljGnxVA',
        'https://disk.yandex.com/i/HTbyYRjJK0nTqA',
        'https://disk.yandex.com/i/X15_3MwW6QA1hA',
        'https://disk.yandex.com/i/ipAWv4VyeUGE9Q',
        'https://disk.yandex.com/i/MfAvL2sXhZECrQ',
        'https://disk.yandex.com/i/EexiQv9IZuShrA',
    ],
    'sleep': [
        'https://disk.yandex.com/i/THDF9fcq0L8asg',
        'https://disk.yandex.com/i/Hbwdwp1zW_u7_Q',
        'https://disk.yandex.com/i/KasPpDk_USOGog',
        'https://disk.yandex.com/i/RxK_QOK7VY1wZQ',
        'https://disk.yandex.com/i/fIUXQrTARqcD8Q',
        'https://disk.yandex.com/i/lwtTL3M-R4M0_w',
        'https://disk.yandex.com/i/RVsx9buC-OWTBw',
        'https://disk.yandex.com/i/skdgC5xc4ycXEw',
        'https://disk.yandex.com/i/PTwNrSs03C-DkQ',
        'https://disk.yandex.com/i/F1W7uKVq_fSwUQ',
        'https://disk.yandex.com/i/7t8NwcQZaI9JuQ',
        'https://disk.yandex.com/i/jrpDo_XyoZZaGg',
        'https://disk.yandex.com/i/AEx3S27sCYVtRA',
        'https://disk.yandex.com/i/0xSDatICgd-A4Q',
        'https://disk.yandex.com/i/jIIBonh_BAiF1g',
        'https://disk.yandex.com/i/nhHFytIHEHeNww',
        'https://disk.yandex.com/i/xtaawY6XnbeyiQ',
        'https://disk.yandex.com/i/eVWvA3hy_SxwLQ',
        'https://disk.yandex.com/i/AqXZ0WDQLgamxg',
        'https://disk.yandex.com/i/9-qPJnAhc8YMGg',
    ],
}

# ── Message text pools (one is picked at random each time) ───────────────────
TEXTS = {
    'pill_reminder': [
        "Лизочка, пора принять таблеточку! 💊",
        "Милая, не забудь про таблетку, пожалуйста! 🌸",
        "Котечка, время для твоей таблеточки! ✨",
        "Лисстик, выпей таблетку, солнце мое! 💕",
        "Моя Любимая, пора позаботиться о своем здоровье! 💊",
        "Звездочка моя, таблеточка сама себя не выпьет! 🌟",
        "Мурочка, скорее запивай таблеточку водичкой! 💧",
        "Заечка, пришло время для пилюли! 🐰",
        "Листочек, не забываем про важные дела — пора пить таблетку! 🌿",
        "Моя чудесная девочка, таблеточка ждет! 💖",
    ],
    'taken': [
        "Умничка моя, так держать! 🌟",
        "Солнышко мое, какая ты молодец! ☀️",
        "Лизочка, ты просто лучшая! Горжусь! 💖",
        "Моя Звездочка, самая послушная девочка! ⭐",
        "Котечка, ты невероятная! 😻",
        "Лисстик, так держать, горжусь тобой! 🦊",
        "Мурка моя, умница! 💕",
        "Любимая, ты прекрасно справилась! 💪",
        "Заечка, спасибо, что заботишься о себе! 🐰",
        "Листочек мой, ты чудо! 🌿",
        "Мурочка, я так рад, что ты выпила! 🥰",
        "Милая, это маленькая, но очень важная победа! 🌸",
    ],
    'missed': [
        "Очень жаль, но не расстраивайся, Лизочка! Завтра обязательно получится! 💕",
        "Ничего страшного, Милая! Главное — не забудь завтра! 🌸",
        "Не переживай, Котечка! Все в порядке, у нас еще столько дней впереди! ✨",
        "Лисстик, бывает и так! Обнимаю тебя крепко! 🦊",
        "Моя Любимая, все хорошо! Завтра точно справимся! 💖",
        "Заечка, просто постарайся завтра вспомнить, ладно? 🐰",
        "Мурочка, не ругай себя, ты все равно самая лучшая! 😻",
        "Звездочка, мы это исправим завтра! ⭐",
    ],
    'persistent': [
        "Лизочка, таблеточка все еще ждет! Я буду напоминать... 👀",
        "Котечка, может быть сейчас? Таблетка очень просится! 💊",
        "Лисстик, я все еще здесь! Пожалуйста, не откладывай! 🦊",
        "Милая, я буду писать, пока ты не нажмешь заветную кнопочку! 💕",
        "Любимая, давай уже, это займет всего секунду! Я верю в тебя! 💪",
        "Мурочка, ну пожалуйста! Запей ее водичкой скорее! 💧",
        "Заечка, ну чего ты тянешь? Пилюля плачет! 🐰",
        "Листочек мой, ну давай, я жду твой клик! 🌿",
        "Звездочка, сделай это прямо сейчас, я очень прошу! ⭐",
        "Упрямая моя Котечка, я ведь не отстану! 😻",
    ],
    'motivation': [
        "Лизочка, ты огромная молодец! Ты лучше всех на свете! 🌟",
        "Моя Звездочка, ты самая красивая и самая прекрасная во всей Вселенной! ✨",
        "Котечка, у тебя все получится! Все твои мечты обязательно сбудутся! 💫",
        "Лисстик, ты всех порвешь! Ты невероятная и потрясающая! 🔥",
        "Милая, ты самая сильная! Я в тебя верю всем сердцем! 💪",
        "Любимая, ты делаешь все правильно! Я всегда на твоей стороне! 💖",
        "Лиза, ты просто космос! Продолжай светить так же ярко! 🚀",
        "Мурка моя, ты справишься абсолютно со всем! Ты лучшая девочка на свете! 😻",
        "Мурочка, мир у твоих ног! Смело иди к своим целям! ☀️",
        "Заечка, каждый твой шаг делает тебя только лучше. Горжусь тобой! 🐰",
        "Листочек, ты растешь и расцветаешь с каждым днем! 🌿",
        "Ты мое самое большое вдохновение, Любимая! 🥰",
    ],
    'quotes': [
        "Каждый день — это новая чудесная возможность стать еще счастливее! 🌅",
        "Ты намного сильнее, чем можешь себе представить! 💪",
        "Маленькие шаги каждый день ведут к твоим самым большим победам! 🏆",
        "Верь в себя так же крепко, как я верю в тебя! 💕",
        "Твоя целеустремленность вдохновляет! 🌟",
        "Сегодня просто потрясающий день, чтобы искренне улыбнуться! 😊",
        "За каждой тучей всегда прячется солнце! ☀️",
        "Даже самый длинный путь начинается с одного твоего шага! 🐾",
    ],
    'sleep_question': [
        "Какие планы на завтра, Милая? Во сколько планируешь ложиться спатки? 🌙💤",
        "Моя Звездочка, во сколько завтра собираешься лечь в кроватку? ✨",
        "Котечка, скажи-ка, когда мы завтра отправляемся в царство Морфея? 😻",
        "Лизочка, распределяем время на завтра! Во сколько спать? 📝",
        "Заечка, график сна сам себя не построит! Во сколько ложимся? 🐰",
    ],
    'sleep_reminder': [
        "Лизочка, тащи свою прекрасную жопку в кроватку! 😴",
        "Котечка, пора баиньки! Завтра ждет потрясающий день! ✨",
        "Любимая, не задерживайся, пора закрывать глазки! 🌙",
        "Милая, завтра много дел — твоему организму нужен качественный отдых! 💕",
        "Мурочка, лучше доделать все завтра со свежей головой, а сейчас в постельку! 😊",
        "Лисстик, сон крайне важен для твоей невероятной красоты! Бегом спать! 🦊",
        "Звездочка, не забывай про отдых — ты нужна этому миру бодрой и счастливой! ☀️",
        "Мурка моя, время спать! Пусть впереди будут только новые победы! 🌟",
        "Лизочка, твой организм скажет тебе огромное спасибо за ранний сон! 💤",
        "Любимая, в кроватку! Завтра будешь свежей, как утренняя розочка! 🌹",
        "Котечка, хватит сидеть в телефоне — пора в теплую мягкую постельку! 😻",
        "Листочек, отрывайся от дел и топай спать! Завтра будут новые покорения! 🌿",
        "Милая, здоровый сон — это твоя главная инвестиция в завтрашний успех! 📈",
        "Заечка, закругляйся и в кроватку! Я жду тебя в самых сладких снах! 💭",
        "Мурочка, пора отдыхать! Набирайся сил! 🌍",
        "Лисстик, не откладывай отдых — ныряй под одеялко! 🛏️",
        "Любимая, глазки закрываются! Завтра ты снова будешь королевой! 👑",
        "Котечка, сладких и пушистых снов! Пусть приснится что-то волшебное! 🌈",
        "Лизочка, хватит бодрствовать! Тебе пора набираться энергии! 😄",
        "Милая, закрывай глазки! Завтра новый восхитительный день! 🌅",
    ],
}
